<?php

/**
 * @file
 * Implementation de notre hook.
 */




/**
 * Implements hook_theme().
 */
function podtalk_theme ($existing, $type, $theme, $path) {
  return [
    'recettes-liste' => [
      'variables' => [
        'items' => [],
        'title' => '',
      ]
    ],
    'salah' => [
      'variables' => [
        'items' => [],
        'title' => '',
        'nom' => '',
      ]
    ],

    'user-show' => [
      'variables' => [
        'data' => [],
        'title' => '',
        'salah' => '',
    ],
  ],
  ];
}







