custom_config.settings_form:
  path: '/admin/config/system/custom-config'
  defaults:
    _title: 'Configurer les liens sociaux'
    _form: 'Drupal\custom_config\Form\SettingsForm'
  requirements:
    _permission: 'administer custom_config configuration'
